### ISSUE TITLE
Main markdown rules list

### ISSUE THREAD

**Issue by e13mort** [appmattus/markdown-lint#30]
I just tried the plugin and it's a great tool, thanks! It forced me to refactor all of my current markdown files and at the first time I though check rules are way too strict. I got curious about a "source of truth" of the plugin's checks. Where I can find it?

**Comment by mattmook** [comment]
The majority of the rules are based on https://cirosantilli.com/markdown-style-guide/#general-rules and heavily influenced by both https://github.com/DavidAnson/markdownlint and https://github.com/markdownlint/markdownlint.

There were a few places where I was more opinionated, because, well I could be.

**Comment by e13mort** [comment]
Maybe it's worth to be mentioned in the main Readme file. I think there's a chance that somebody will come up with the same question.
I could make a PR if you'd like.

**Comment by mattmook** [comment]
I'm going to work on a GitHub pages site built from the rules documentation and will add something about this then

**Comment by e13mort** [comment]
Alright. Thanks again for the answer
